directory: ~/Musique
library: ~/.beetsmusic.blb
plugins: fetchart lyrics lastgenre mpdstats web discogs chroma smartplaylist info mpdupdate fromfilename duplicates thumbnails

import:
    move: yes
    log: ~/.beetsimport.log

paths:
    singleton: $artist/$title

smartplaylist:
    relative_to: ~/Musique
    playlist_dir: ~/.config/mpd/playlists
    playlists:
        - name: tout.m3u
          query: ''
        - name: sixties.m3u
          query: 'original_year::196.'
        - name: seventies.m3u
          query: 'original_year::197.'
        - name: récent.m3u
          query: 'original_year::20..'
        - name: indie.m3u
          query: 'genre:indie'
        - name: jack white.m3u
          query: ['"Jack White"', '"The White Stripes"', '"The Raconteurs"', '"Dead Weather"']
        - name: français.m3u
          query: ['country:FR', 'language:fra']
